apiVersion: apps/v1
kind: Deployment
metadata:
  name: absa-bookstore
spec:
  selector:
    matchLabels:
      run: absa-bookstore
  replicas: 1
  template:
    metadata:
      labels:
        run: absa-bookstore
    spec:
      containers:
        - name: absa-bookstore
          image: ngonichibamu/absa-bookstore
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m