
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
    generate-ddl: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO