spring:
  datasource:
    url: jdbc:h2:mem:proddb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: prod
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      springframework:
        security: DEBUG